### ISSUE TITLE
Dual arrows (expert mode) not working with Firefox 72.0.2

### ISSUE THREAD

**Issue by grahamperrin** [PoziWorld/Scroll-To-Top-Button-extension#10]
Screen recording: 

[2020-01-19 13:44.zip](https://github.com/PoziWorld/Scroll-To-Top-Button-extension/files/4082735/2020-01-19.13.44.zip)

There's the invitation to restart the extension but the preference is not saved.

**Comment by PoziWorld** [comment]
@grahamperrin, 

Thank you for creating the report right away!

Looking into it now...

**Comment by PoziWorld** [comment]
Figured this one out, [too](https://github.com/PoziWorld/Scroll-To-Top-Button-extension/issues/11#issuecomment-576135107)...

This happens because of a [race condition](https://en.wikipedia.org/wiki/Race_condition):
The invitation to restart the extension appears before the preference is saved, and the invitation stops the execution of the rest of the code while the invitation is on the display.

Will push a fix soon...

**Comment by PoziWorld** [comment]
@grahamperrin,

Version 9.0.1 is now available for download at https://addons.mozilla.org/addon/scroll-to-top-button-extension/.

Thank you again for the timely and detailed report!
