### ISSUE TITLE
i18n services not initialized.

### ISSUE THREAD

**Issue by grahamperrin** [PoziWorld/Scroll-To-Top-Button-extension#11]
With home-built Waterfox Classic 2019.12 (20200103060435) on FreeBSD-CURRENT: 

![2020-01-19 13:36:06](https://user-images.githubusercontent.com/192271/72682216-a84e6d80-3ac2-11ea-95d2-1dcaf458c96a.png)

If I recall correctly, the bug arose after I chose dual arrows (expert mode) and accepted the invitation to restart the extension.

**Comment by PoziWorld** [comment]
Hm... Strange... It's supposed to load the translations first, then show the page.

Will look into it.

Thank you for the report and additional details!

**Comment by PoziWorld** [comment]
Figured this one out...

Both, the Options page and the button, share the same i18n (internationalization) component – code that picks the right language and loads the corresponding translations.

So, what's happening here is this:
1. The Options page figures out what language to use, caches logic for later.
2. The button gets injected, wipes the cached logic.
3. The Options page tries to get translations for each element, but since the the cached logic is gone it fails.

In Chromium-based browsers, the button doesn't get injected onto the Options page, so no issues there.
In Firefox-based browsers, it does, so the issue happens.

Will push a fix soon...

**Comment by PoziWorld** [comment]
@grahamperrin,

Version 9.0.1 is now available for download at https://addons.mozilla.org/addon/scroll-to-top-button-extension/.

Thank you again for the timely and detailed report!
