### ISSUE TITLE
Upload latest version to Firefox Addons center

### ISSUE THREAD

**Issue by Bamajon1974** [PoziWorld/Scroll-To-Top-Button-extension#15]
Can you upload the latest version of Scroll to Top Extension to the Firefox Add-on Center? The Chrome Webstore has a later version. Thanks!

**Comment by PoziWorld** [comment]
Hello @Bamajon1974,

Unfortunately, quite a few Chrome users experience a strange issue, and we've been trying to help resolve the issue and have been pushing a few updates for this, and the issue is still there. 

Don't want to introduce that issue to Firefox users. Will update once it's safe.

Thank you for your concern.

**Comment by PoziWorld** [comment]
Done. 
v10.0.1 is available at https://addons.mozilla.org/addon/scroll-to-top-button-extension/

Thank you for the request!
