### ISSUE TITLE
Scroll To Top Button locks the buttons on the page

### ISSUE THREAD

**Issue by Arku3S** [PoziWorld/Scroll-To-Top-Button-extension#16]
Drop-down lists on https://mangadex.org are not working
Disabling the extension makes the website work properly.

**Comment by PoziWorld** [comment]
@Arku3S, thank you for your report! Will look into it.

**Comment by PoziWorld** [comment]
@Arku3S, could you please specify what drop-down lists you are referring to?

If you could provide a screenshot or, preferably, a video showing the issue, that would help.

Also, if you could share a screenshot of your Scroll To Top Button settings, please.

**Comment by Arku3S** [comment]
I recorded it
[Video](https://www.youtube.com/watch?v=YYBdEjbLXlg)
I would like to add that if you change the options to "keyboard only" in the settings, the problem does not occur.

**Comment by PoziWorld** [comment]
Aha! It's Firefox!
Able to reproduce the issue now.

Will keep you posted.

Thank you for the video – it was helpful.

**Comment by PoziWorld** [comment]
@Arku3S, thank you for your patience.

### Non-technical:
It's caused by the code used on the website.

### Technical:
Seems like it happens because of an outdated ([3-year old](https://github.com/jquery/jquery/releases/tag/3.3.1)) version of a JavaScript library used on the site – jQuery v3.3.1.

Newer versions of the library don't cause this issue:
[Video showing jQuery v3.3.1 causes dropdowns to not work, while jQuery v3.4.0 and jQuery v3.5.1 don't cause such an issue](https://user-images.githubusercontent.com/5961162/106378679-86d1c400-635b-11eb-8cb5-9b0fa8e74c6f.mp4)

### Next steps:
Would you like to reach out to the website developers and ask them to upgrade their library?
Should be straightforward for them to replace and safe, without the need to make any other changes.

**Comment by Arku3S** [comment]
Thanks for the help. He will contact the developer of the website.
